#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

# use dependencies defined in metadata.json
#metadata

# use dependencies defined in Modulefile
# modulefile

# A module from the Puppet Forge
mod 'puppetlabs-postgresql'
mod 'puppetlabs-puppetdb'

# A module from git
mod 'puppetlabs-firewall',
  :git => 'git://github.com/puppetlabs/puppetlabs-firewall.git'

mod 'local-role_postgresql_server_puppetdb',
  :path => './roles/role_postgresql_server_puppetdb'

mod 'local-role_puppetdb_server',
  :path => './roles/role_puppetdb_server'

mod 'local-role_puppet_master',
  :path => './roles/role_puppet_master'

mod 'local-profile_common',
  :path => './profiles/profile_common'

mod 'local-profile_postgresql_server_puppetdb',
  :path => './profiles/profile_postgresql_server_puppetdb'

mod 'local-profile_postgresql_client',
  :path => './profiles/profile_postgresql_client'

mod 'local-profile_puppetdb',
  :path => './profiles/profile_puppetdb'

mod 'local-profile_puppet_master',
  :path => './profiles/profile_puppet_master'

# A module from a git branch/tag
# mod 'puppetlabs-apt',
#   :git => 'https://github.com/puppetlabs/puppetlabs-apt.git',
#   :ref => '1.4.x'

# A module from Github pre-packaged tarball
# mod 'puppetlabs-apache', '0.6.0', :github_tarball => 'puppetlabs/puppetlabs-apache'
