#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

# use dependencies defined in metadata.json
#metadata

# use dependencies defined in Modulefile
# modulefile

# Modules from the Puppet Forge
mod 'puppetlabs-postgresql'
mod 'puppetlabs-ntp'
mod 'stahnma-epel'
mod 'puppetlabs-apache'
#mod 'puppetlabs-firewall'
#mod 'puppetlabs-puppetdb'
#mod 'stephenrjohnson-puppet'
#mod 'nibalizer-puppetboard'

# Modules from git
mod 'puppetlabs-firewall',
  :git => 'git://github.com/puppetlabs/puppetlabs-firewall.git'

mod 'yo61-puppet',
  :git => 'git://github.com/yo61/puppetmodule.git',
  :ref => 'feature/make_ssl_setup_optional'

mod 'yo61-puppetdb',
  :git => 'git://github.com/yo61/puppetlabs-puppetdb.git',
  :ref => 'feature/add_ssl_cert_settings'

mod 'yo61-puppetboard',
  :git => 'git://github.com/yo61/puppet-module-puppetboard.git',
  :ref => 'feature/rename_puppetdb_ssl_to_puppetdb_ssl_verify'

# Roles (from local dir)
mod 'local-role_postgresql_server_puppetdb',
  :path => './local/roles/role_postgresql_server_puppetdb'

mod 'local-role_puppetdb_server',
  :path => './local/roles/role_puppetdb_server'

mod 'local-role_puppet_master',
  :path => './local/roles/role_puppet_master'

mod 'local-role_puppetboard',
  :path => './local/roles/role_puppetboard'

# Profiles (from local dir)
mod 'local-profile_common',
  :path => './local/profiles/profile_common'

mod 'local-profile_postgresql_server_puppetdb',
  :path => './local/profiles/profile_postgresql_server_puppetdb'

mod 'local-profile_postgresql_client',
  :path => './local/profiles/profile_postgresql_client'

mod 'local-profile_puppetdb',
  :path => './local/profiles/profile_puppetdb'

mod 'local-profile_puppet_master',
  :path => './local/profiles/profile_puppet_master'

mod 'local-profile_ntp',
  :path => './local/profiles/profile_ntp'

mod 'local-profile_puppet_agent',
  :path => './local/profiles/profile_puppet_agent'

mod 'local-profile_puppetboard',
  :path => './local/profiles/profile_puppetboard'

# A module from a git branch/tag
# mod 'puppetlabs-apt',
#   :git => 'https://github.com/puppetlabs/puppetlabs-apt.git',
#   :ref => '1.4.x'

# A module from Github pre-packaged tarball
# mod 'puppetlabs-apache', '0.6.0', :github_tarball => 'puppetlabs/puppetlabs-apache'
